---
title: "Enjoying cleaning your data with Detre"
output: html_document
---


Data scientists mention that one of the least enjoyable parts of their work is data cleaning. Several surveys ([1](https://visit.figure-eight.com/rs/416-ZBE-142/images/Crowdflower_Data_Scientist_Survey2015.pdf),
[2](https://visit.figure-eight.com/rs/416-ZBE-142/images/CrowdFlower_DataScienceReport_2016.pdf),
[3](https://visit.figure-eight.com/rs/416-ZBE-142/images/CrowdFlower_DataScienceReport.pdf),
[4](https://www.anaconda.com/state-of-data-science-2020?utm_medium=press&utm_source=anaconda&utm_campaign=sods-2020&utm_content=report)) have recorded this sentiment over time, and it has not changed. Not only do they not enjoy data cleaning, but it also happens to form part of the bulk of the work they need to do. Nonetheless, they do have powerful and valuable tools at their disposal to get the job done.

Now imagine how someone who is not a data scientist working with data feels about data cleaning? Take, for example, this [post](https://www.mrexcel.com/board/threads/how-to-clean-up-and-format-very-messy-date-and-non-date-date.1017938/) where a user has to clean the dates of their data set. The post shows messy dates and the desired respective clean dates. Making the necessary transformations to get clean dates is a challenging if the dataset has 100s or 1000s of rows. They will need to have above average skills in Excel or may use a programming language such as Python or R. Learning to program or develop above-average skills in Excel does take time; meanwhile, the deadline is looming.

The situation the user above faces is often met by several people who need to make such challenging data cleaning transformations. Having a tool that will make it easy and intuitive to clean your data will be indispensable to people's toolkits. Hence the birth of Detre.

Detre will allow people to clean their small to medium-sized data with relative ease. The user will not be expected to have any coding skills or remember Excel/Google sheets formulas. There will only need to upload their data and guide the platform to their desired output.

Our vision is to half the time spent on cleaning data. Are you joining us on this mission? See our [YouTube channel](https://www.youtube.com/channel/UCB4xcEMbw-0-pLzKfvDHFbw) on what we are building. 